<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="css/stylesheet.css">
	<title>Yoobee's Calculator</title>
</head>
<body>
		<div class = "container">

			<header>
					<img src = "img/logo.png" alt = "yoobee logo" >
					<br><br>
					<h1>Calculator</h1>
			</header>

					<div class = "greetingdiv"> 

				<?php 
					date_default_timezone_set('Pacific/Auckland');
					$hour = date('G');
					if ( $hour >= 5 && $hour <= 11.59 ) {
					   $greetings = "<b>Good Morning</b>";
					} else if ( $hour >= 12 && $hour <= 17 ) {
					   $greetings =  "<b>Good Afternoon</b>";
					} else if ( $hour >= 17.01 && $hour <= 23.59 ) {
					   $greetings = "<b>Good Evening</b>";
					} else {
					   $greetings = "<b>Good Night</b>";
					}
					echo $greetings . "<br>";
					echo "Today is " . date("l d/m/y ");
					echo " & the current time is " . date("h:i:sa") . "<br>";
				?>

			</div>			
		<br>
		<div class = "formcontainer">
		
			<form action = "test.php" method = "get">
			<h3>Select shape:</h3>

			<div class = "radiodiv">
				<input type = "radio" checked = "checked" name = "shape" value = "circle" class = "radiobtn"><p>Circle</p>
				<input type = "radio" name = "shape" value = "square" class = "radiobtn"><p>Square</p>
				<input type = "radio" name = "shape" value = "rectangle" class = "radiobtn"><p>Rectangle</p>
						</div>

			<div class = "containerinput"> 
				<h3>Select calculator:</h3>
			<p>Circle Calculator</p>
			<input type = "text" name = "radius" placeholder = "Enter radius value ..." id= "text1" />

			<p>Square Calculator</p>
			<input type = "text" name = "side" placeholder = "Enter side value ..." id = "text2" />

			<p>Rectangle Calculator</p>
			<input type = "text" name = "length" placeholder = "Enter length value ..." id = "text3" /><br>
			<input type = "text" name = "breadth" placeholder = "Enter breadth value ..." id = "text4" />
			</div>

			<input type="submit" id = "submitbutton">  
			</form>
		
		</div>

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src = "formfunction.js"></script>
</body>
</html>